genome: "hg38"

# Specify the ABSOLUTE PATH of input files using variable path expressions
# Entries correspond to values in the data_source column in sample_annotation table
# {variable} can be used to replace environment variables or other sample_annotation columns
# If you use {variable} codes, you should quote the field so python can parse it.
data_sources:
  bsf: /scratch/lab_bsf/samples/{flowcell}/{flowcell}_{lane}_samples/{flowcell}_{lane}#{BSF_name}.bam
  bsf_test: /scratch/users/berguener/junk/varcall_test/{raw_bam}

# The following section contains configurations that will be saved in inputs.json file as they are
# You can configure inputs of various tasks directly from this section
bypass_parser:
  variant_calling.ref_fasta: "/scratch/lab_bsf/resources/GATK/hg38/v0/Homo_sapiens_assembly38.fasta"
  variant_calling.ref_fai: "/scratch/lab_bsf/resources/GATK/hg38/v0/Homo_sapiens_assembly38.fasta.fai"
  variant_calling.ref_alt: "/scratch/lab_bsf/resources/GATK/hg38/v0/Homo_sapiens_assembly38.fasta.64.alt"
  variant_calling.ref_amb: "/scratch/lab_bsf/resources/GATK/hg38/v0/Homo_sapiens_assembly38.fasta.64.amb"
  variant_calling.ref_ann: "/scratch/lab_bsf/resources/GATK/hg38/v0/Homo_sapiens_assembly38.fasta.64.ann"
  variant_calling.ref_bwt: "/scratch/lab_bsf/resources/GATK/hg38/v0/Homo_sapiens_assembly38.fasta.64.bwt"
  variant_calling.ref_pac: "/scratch/lab_bsf/resources/GATK/hg38/v0/Homo_sapiens_assembly38.fasta.64.pac"
  variant_calling.ref_sa: "/scratch/lab_bsf/resources/GATK/hg38/v0/Homo_sapiens_assembly38.fasta.64.sa"
  variant_calling.ref_dict: "/scratch/lab_bsf/resources/GATK/hg38/v0/Homo_sapiens_assembly38.dict"
  variant_calling.dbsnp_vcf: "/scratch/lab_bsf/resources/GATK/hg38/v0/dbsnp_146.hg38.vcf.gz"
  variant_calling.dbsnp_idx: "/scratch/lab_bsf/resources/GATK/hg38/v0/dbsnp_146.hg38.vcf.gz.tbi"
  variant_calling.gatk_jar: "/scratch/users/berguener/bin/gatk-4.1.8.1/gatk-package-4.1.8.1-local.jar"
  variant_calling.annotate_vcf_vep.vep_executable: "/scratch/lab_bsf/modules/applications/ensembl/100/ensembl-vep/vep"
  variant_calling.annotate_vcf_vep.dir_cache: "/scratch/lab_bsf/resources/VEP"
  variant_calling.annotate_vcf_vep.dir_plugins: "/scratch/lab_bsf/modules/applications/ensembl/100/VEP_plugins"
  variant_calling.annotate_vcf_vep.CADD_SNVs: "/scratch/lab_bsf/resources/CADD/hg38/1.6/whole_genome_SNVs.tsv.gz"
  variant_calling.annotate_vcf_vep.CADD_indels: "/scratch/lab_bsf/resources/CADD/hg38/1.6/gnomad.genomes.r3.0.indel.tsv.gz"
  variant_calling.annotate_vcf_vep.fasta: "/scratch/lab_bsf/resources/VEP/homo_sapiens_merged/100_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz"
  variant_calling.annotate_vcf_vep.assembly: "GRCh38"