genome_version: "hg38"

# Specify the ABSOLUTE PATH of input files using variable path expressions
# Entries correspond to values in the data_source column in sample_annotation table
# {variable} can be used to replace environment variables or other sample_annotation columns
# If you use {variable} codes, you should quote the field so python can parse it.
data_sources:
  bsf: /nobackup/lab_bsf/samples/{flowcell}/{flowcell}_{lane}_samples/{flowcell}_{lane}#{BSF_name}.bam
  bsf_test: /nobackup/lab_bsf/users/berguener/junk/varcall_test/{raw_bam}

# The following section contains configurations that will be saved in inputs.json file as they are
# You can configure inputs of various tasks directly from this section
bypass_parser:
  variant_calling.rt_image: "/nobackup/lab_bsf/users/berguener/singularity/bsf_variant_calling_0.3.sif"
  variant_calling.ref_fasta: "/nobackup/lab_bsf/resources/GATK/hg38/v0/Homo_sapiens_assembly38.fasta"
  variant_calling.ref_fai: "/nobackup/lab_bsf/resources/GATK/hg38/v0/Homo_sapiens_assembly38.fasta.fai"
  variant_calling.ref_alt: "/nobackup/lab_bsf/resources/GATK/hg38/v0/Homo_sapiens_assembly38.fasta.64.alt"
  variant_calling.ref_amb: "/nobackup/lab_bsf/resources/GATK/hg38/v0/Homo_sapiens_assembly38.fasta.64.amb"
  variant_calling.ref_ann: "/nobackup/lab_bsf/resources/GATK/hg38/v0/Homo_sapiens_assembly38.fasta.64.ann"
  variant_calling.ref_bwt: "/nobackup/lab_bsf/resources/GATK/hg38/v0/Homo_sapiens_assembly38.fasta.64.bwt"
  variant_calling.ref_pac: "/nobackup/lab_bsf/resources/GATK/hg38/v0/Homo_sapiens_assembly38.fasta.64.pac"
  variant_calling.ref_sa: "/nobackup/lab_bsf/resources/GATK/hg38/v0/Homo_sapiens_assembly38.fasta.64.sa"
  variant_calling.ref_dict: "/nobackup/lab_bsf/resources/GATK/hg38/v0/Homo_sapiens_assembly38.dict"
  variant_calling.dbsnp_vcf: "/nobackup/lab_bsf/resources/GATK/hg38/v0/dbsnp_146.hg38.vcf.gz"
  variant_calling.dbsnp_idx: "/nobackup/lab_bsf/resources/GATK/hg38/v0/dbsnp_146.hg38.vcf.gz.tbi"
  variant_calling.tools_folder: "/home/berguener/src/variant_calling_pipeline/tools/"
  variant_calling.annotate_vcf_vep.vep_executable: "vep"
  variant_calling.annotate_vcf_vep.dir_cache: "/nobackup/lab_bsf/resources/VEP"
  variant_calling.annotate_vcf_vep.dir_plugins: "/nobackup/lab_bsf/resources/VEP/Plugins_103"
  variant_calling.annotate_vcf_vep.CADD_SNVs: "/nobackup/lab_bsf/resources/CADD/hg38/1.6/whole_genome_SNVs.tsv.gz"
  variant_calling.annotate_vcf_vep.CADD_indels: "/nobackup/lab_bsf/resources/CADD/hg38/1.6/gnomad.genomes.r3.0.indel.tsv.gz"
  variant_calling.annotate_vcf_vep.vcf_clinvar: "/nobackup/lab_bsf/resources/ClinVar/hg38/clinvar_20210213.vcf.gz"
  variant_calling.annotate_vcf_vep.fasta: "/nobackup/lab_bsf/resources/VEP/homo_sapiens_merged/103_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz"
  variant_calling.annotate_vcf_vep.assembly: "GRCh38"
  variant_calling.annotate_vcf_vep.rt_image: "/nobackup/lab_bsf/users/berguener/singularity/ensembl-vep_release_103.0.sif"